spring:
  config:
    import: classpath:/env.properties
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB-CLIENT-ID}
            clientSecret: ${GITHUB-CLIENT-SECRET}
            scope:
              - read:user
              - user:email

          google:
            client-id: ${GOOGLE-CLIENT-ID}
            client-secret: ${GOOGLE-CLIENT-SECRET}
